function RNA(DNA) {
 for (var i = 0; i<DNA.length; i++) {
    DNA = DNA.replace('T','U');
 }
console.log(DNA)
}

RNA('GGCAGATTCCCCCTAGACCCGCCCGCACCATGGTCAGGCATGCCCCTCCTCATCGCTGGGCACAGCCCAGAGGGTATAAACAGTGCTGGAGGCTGGCGGGGCAGGCCAGCTGAGTCCTGAGCAGCAGCCCAGCGCAGCCACCGAGACACCATGAGAGCCCTCACACTCCTCG')